apiVersion: v1
kind: ConfigMap
metadata:
  name: hackathon-settings
data:
  settings.yaml: |
    db-username: #{db-username}
    db-password: #{db-password}
    db-name: #{db-name}
    paypal-gateway: #{paypal-gateway}
    env-name: #{env-name}
