apiVersion: v1
kind: ConfigMap
metadata:
  name: hackathon-settings
data:
  settings.yaml: |
    db-username: admin
    db-password: changeme
    db-name: app_db
    paypal-gateway: sandbox
    env-name: development
