apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon
  labels:
    app: hackathon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
        - name: hackathon
          image: ghcr.io/kostis-codefresh/hackathon:#{Octopus.Action.Package[hackathon].PackageVersion}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: settings
              mountPath: /app/settings.yaml
              subPath: settings.yaml
      volumes:
        - name: settings
          configMap:
            name: hackathon-settings
